version: "3"
services:
# region Web Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: social-meta-client
    ports:
      - "3000:3000"
      # - "3000:80" # If we use with nginx..
    depends_on:
      - app
    networks:
      - social-meta-network
    restart: always

# region Backend Server
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: social-meta-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - social-meta-network
    command: "node dist/server.js"
    volumes:
      - "./server:/app"
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongodb:27017/socialMeta
      - NODE_ENV=development
    working_dir: /app
    restart: always
    links:
      - mongodb

# region Database Server
  mongodb:
    image: mongo:latest
    container_name: social-meta-mongodb
    ports:
      - "27017:27017"
    networks:
      - social-meta-network
    restart: always
    volumes:
      - /usr/local/var/mongodb:/data/db

networks:
  social-meta-network:
