name: Deploy Backend API to Render

on:
  push:
    branches: [deploy]

jobs:
  deploy:
    name: Trigger Render Deploy Hook
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Trigger Deploy Hook to Render
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
